# Do not modify this file!  It was generated by enixos-generate-configf
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{modulesPath, ...}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Use the systemd-boot EFI boot loader.
  boot = {
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;

    initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = [];
    extraModulePackages = [];
    # crashDump.enable = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e95f4d39-1b0e-4b8b-8e44-445b5cd06c9c";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5488-9597";
    fsType = "vfat";
  };

  #fileSystems."/mnt/hdd" = {
  #  device = "/dev/disk/by-label/SubData";
  #  fsType = "ntfs";
  #};

  #fileSystems."/mnt/hdd2" = {
  #  device = "/dev/disk/by-uuid/c8ecd6c2-4467-4c7d-a76d-f116167268d3";
  #  fsType = "ext4";
  #};

  swapDevices = [
    {device = "/dev/disk/by-uuid/6089d878-2901-455c-804e-0e8b9cedcd79";}
  ];
}
