# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Bootloader.
  boot = {
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
    initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
    kernelPackages = pkgs.linuxPackages_latest;

    extraModprobeConfig = ''
      options snd slots=snd-hda-intel
    '';
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/2f57a18e-ef09-46f5-a271-95f3b4595c8a";
      fsType = "xfs";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/942E-4BC7";
      fsType = "vfat";
    };

    "/mnt/hdd" = {
      device = "/dev/disk/by-label/SubData";
      fsType = "ntfs";
    };

    "/mnt/hdd2" = {
      device = "/dev/disk/by-uuid/c8ecd6c2-4467-4c7d-a76d-f116167268d3";
      fsType = "ext4";
    };
  };

  swapDevices = [{device = "/dev/disk/by-uuid/4d538c4d-9ca3-452e-9e64-026efd9e57d8";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  hardware.enableAllFirmware = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
