{ config, pkgs, ...}:

{
  home = {
    username = "kori";
    homeDirectory = "/home/kori";
  };

  wayland.windowManager.hyprland = {
     enable = true;
     extraConfig = ''
       autogenerated = 0
     '';
  };
  
  home.stateVersion = "23.05";
  programs.home-manager.enable = true;
}
