{ config, pkgs, ... }:

{
  home = {
    username = "kaguya";
    homeDirectory = "/home/kaguya";
  };

  wayland.windowManager.hyprland = {
    enable = true;
    extraConfig = ''
      autogenerated = 0
    '';
  };
  programs.fish.enable = true;
  programs.emacs = {
    enable = true;
    package = pkgs.emacs29-pgtk;
    extraPackages = epkgs: [
      epkgs.vterm
    ];
  };

  home.stateVersion = "23.05";
  programs.home-manager.enable = true;
}
