_: {
  home = {
    username = "kori";
    homeDirectory = "/home/kori";
    stateVersion = "23.05";
  };

  programs = {
    fish.enable = true;
    direnv = {
      enable = true;
      nix-direnv.enable = true;
    };

    home-manager.enable = true;
  };

  # wayland.windowManager.hyprland = {
  #  enable = true;
  #  extraConfig = ''
  #    autogenerated = 0
  #    # exec-once = /etc/nixos/hosts/Folkroll/boot.sh
  #    monitor = ,1366x768@60,auto,auto
  #  '';
  #};
}
