{
  config,
  pkgs,
  ...
}: {
  home = {
    username = "kori";
    homeDirectory = "/home/kori";
  };

  programs.fish.enable = true;

  # wayland.windowManager.hyprland = {
  #  enable = true;
  #  extraConfig = ''
  #    autogenerated = 0
  #    # exec-once = /etc/nixos/hosts/Folkroll/boot.sh
  #    monitor = ,1366x768@60,auto,auto
  #  '';
  #};

  home.stateVersion = "23.05";
  programs.home-manager.enable = true;
}
